Rework xcode test

diff --git a/.github/workflows/swift-test.yml b/.github/workflows/swift-test.yml
--- a/.github/workflows/swift-test.yml
+++ b/.github/workflows/swift-test.yml
@@ -72,12 +72,12 @@ jobs:
     runs-on: macos-12
     strategy:
       matrix:
-        destination:
-          - platform=macOS
-          - platform=iOS Simulator,OS=latest,name=iPhone 13 Pro
-          - platform=iOS Simulator,OS=latest,name=iPad Pro (11-inch) (3rd generation)
-          - platform=tvOS Simulator,OS=latest,name=Apple TV 4K (2nd generation)
-          - platform=watchOS Simulator,OS=latest,name=Apple Watch Series 7 (45mm)
+        platform:
+          - macOS
+          - iOS
+          - iPadOS
+          - tvOS
+          - watchOS
     steps:
       - uses: maxim-lobanov/setup-xcode@v1.5.1
         with:
@@ -88,20 +88,53 @@ jobs:
       - name: Read Swift Version
         uses: sersoft-gmbh/swift-version-action@v2.0.1
         id: swift-version
+      - name: Compose destination
+        id: destination
+        env:
+          PLATFORM: ${{ matrix.platform }}
+        run: |
+          if [ "${PLATFORM}" == 'macOS' ]; then
+            echo "xcode=platform=${PLATFORM}" >> "${GITHUB_OUTPUT}"
+            echo "cache-key=platform-${PLATFORM}" >> "${GITHUB_OUTPUT}"
+          else
+            REAL_PLATFORM="${PLATFORM}"
+            DEV_NAME=''
+            case "${PLATFORM}" in
+              'iOS')
+                DEV_NAME='iPhone 13 Pro'
+                ;;
+              'iPadOS')
+                REAL_PLATFORM='iOS'
+                DEV_NAME='iPad Pro (11-inch) (3rd generation)'
+                ;;
+              'tvOS')
+                DEV_NAME='Apple TV 4K (2nd generation)'
+                ;;
+              'watchOS')
+                DEV_NAME='Apple Watch Series 7 (45mm)'
+                ;;
+              *)
+                echo "::error title=Unknown platform!::Unknown platform: ${PLATFORM}"
+                exit 1
+                ;;
+            esac
+            echo "xcode=platform=${REAL_PLATFORM} Simulator,OS=latest,name=${DEV_NAME}" >> "${GITHUB_OUTPUT}"
+            echo "cache-key=platform-${REAL_PLATFORM}-device-$(echo "${DEV_NAME}" | tr -d ' ')" >> "${GITHUB_OUTPUT}"
+          fi
       - uses: actions/checkout@v3.1.0
       - uses: actions/cache@v3.0.11
         with:
           path: .derived-data
-          key: ${{ runner.os }}-${{ steps.os-version.outputs.version }}-xcode-${{ steps.swift-version.outputs.version }}-${{ matrix.destination }}-${{ hashFiles('**/Package.resolved') }}
+          key: ${{ runner.os }}-${{ steps.os-version.outputs.version }}-xcode-${{ steps.swift-version.outputs.version }}-${{ steps.destination.outputs.cache-key }}-${{ hashFiles('**/Package.resolved') }}
           restore-keys: |
-            ${{ runner.os }}-${{ steps.os-version.outputs.version }}-xcode-${{ steps.swift-version.outputs.version }}-${{ matrix.destination }}-
+            ${{ runner.os }}-${{ steps.os-version.outputs.version }}-xcode-${{ steps.swift-version.outputs.version }}-${{ steps.destination.outputs.cache-key }}-
       - uses: sersoft-gmbh/xcodebuild-action@v2.0.1
         with:
           spm-package: './'
           scheme: apple-device-information
-          destination: ${{ matrix.destination }}
+          destination: ${{ steps.destination.outputs.xcode }}
           action: test
-          parallel-testing-enabled: ${{ !contains(matrix.destination, 'watchOS') }}
+          parallel-testing-enabled: ${{ matrix.platform != 'watchOS' }}
           enable-code-coverage: true
           derived-data-path: .derived-data
       - uses: sersoft-gmbh/swift-coverage-action@v3.0.1
